#!/bin/bash
# This is a simple build script, place your post-deploy but pre-start commands
# in this script.  This script gets executed directly, so it could be python,
# php, ruby, etc.
#

set -e 

# Secure some settings
mkdir -p  $OPENSHIFT_REPO_DIR/php/Symfony/app/cache
chmod -v 777 $OPENSHIFT_REPO_DIR/php/Symfony/app/cache
